### ISSUE TITLE
KeyError while sorting duplicate imports

### ISSUE THREAD

**Issue by zsol** [facebookexperimental/usort#194]
On this file:
```
from a import x
from b import y
from b import y
from c import x
```

`usort` fails with
```
Traceback (most recent call last):
  File "usort/cli.py", line 80, in list_imports
    blocks = sorter.sortable_blocks(mod.body)
  File "usort/sorting.py", line 192, in sortable_blocks
    current = self.split_inplace(current, overlap)
  File "usort/sorting.py", line 169, in split_inplace
    new.imported_names[key] = block.imported_names.pop(key)
KeyError: 'y'
```

**Comment by zsol** [comment]
The problem is that [this code](https://github.com/facebookexperimental/usort/blob/d0d551f948ecde94084736a67e357a2777d30a4a/usort/sorting.py#L154-L166) assumes that the newly split block doesn't have shadowing. This assumption isn't satisified by the logic [here](https://github.com/facebookexperimental/usort/blob/d0d551f948ecde94084736a67e357a2777d30a4a/usort/sorting.py#L186).

We either need to fix `name_overlap()` to provide this assumption or `split_inplace()` to not need it.
